// Solution portfolio: what is sold, where it lives in the chain, how it is demonstrated on the twins.
// `match` picks the components a solution instruments (by name); `demo` is the deep link used by "See it live".
window.SOLUTIONS=[
 {id:'pdm',tag:'PdM',name:'Predictive Maintenance',short:'RUL and failure-mode models on rotating and static equipment.',stages:['upstream','midstream','downstream'],
  match:/pump|compressor|motor|drive|reducer|gearbox|drawworks|top drive|rotary|turbine|generator|fan|cooler|expander|crank|beam|bearing|brake/i,
  what:'Machine-learning models on vibration, temperature, current and process tags estimate remaining useful life per failure mode and raise work orders before a trip.',
  how:['PI / historian tags streamed to the edge','Per-asset baselines and failure-mode models','RUL with P10/P90 pushed to CMMS as work orders','Twin shows the prediction on the component'],
  outcomes:[['Unplanned downtime','-35%'],['Maintenance spend','-12%'],['Time to first model','6 weeks']],demo:'#/rig/HS.dw'},
 {id:'anomaly',tag:'Anomaly',name:'Anomaly & Alarm Rationalisation',short:'Multivariate baselines; alarm floods become ranked, explained events.',stages:['upstream','midstream','downstream'],
  match:/./,
  what:'Unsupervised models learn each asset\'s normal operating envelope across all its tags. Deviations are ranked, correlated across assets and explained in plain language; nuisance alarms are suppressed.',
  how:['Multivariate envelope per asset','Cross-asset correlation and ranking','Alarm shelving rules generated from history','Explained events in the copilot'],
  outcomes:[['Nuisance alarms','-70%'],['Mean time to diagnose','-55%'],['Operator load','-40%']],demo:'#/production/SP.ht'},
 {id:'copilot',tag:'Copilot',name:'Operations Copilot',short:'GenAI over P&IDs, manuals, procedures and live data.',stages:['upstream','midstream','downstream'],
  match:/./,
  what:'A retrieval-augmented assistant grounded in the plant\'s documents and its live tags. It explains why an anomaly is happening, drafts the work order, briefs the shift and answers fleet-level questions.',
  how:['Document ingestion: P&IDs, manuals, SOPs, permits','Live-tag context from the twin','Guardrails: cites sources, never actuates','Available in every view'],
  outcomes:[['Root-cause time','minutes, not hours'],['Shift handover prep','-60%'],['Procedure lookups','instant']],demo:'#/gasplant/NG.expander'},
 {id:'prodopt',tag:'Prod-Opt',name:'Production Optimisation',short:'Artificial-lift tuning, well surveillance, deferment tracking.',stages:['upstream'],
  match:/pump|esp|vsd|wellhead|tree|choke|flowline|separator|manifold/i,
  what:'Well and lift models tune set-points (speed, frequency, choke) against constraints and track every barrel of deferment to its cause.',
  how:['Well test and lift data reconciled','Set-point recommendations with guardrails','Deferment ledger by cause','Twin shows lift health per well'],
  outcomes:[['Production','+3-6%'],['Lift energy','-8%'],['Deferment visibility','100%']],demo:'#/production/AL.pj'},
 {id:'pipeline',tag:'Pipeline',name:'Pipeline Integrity & Leak Detection',short:'ILI analytics, corrosion growth, mass-balance leak detection.',stages:['midstream'],
  match:/pipe|flowline|header|rack|pig|trestle|loading line|manifold/i,
  what:'Inline-inspection data, corrosion growth models and real-time mass-balance and pressure-wave leak detection on every segment.',
  how:['ILI run alignment and growth modelling','Real-time leak detection on SCADA','Risk-ranked dig list','Twin shows wall-loss per segment'],
  outcomes:[['Leak detection','< 5 min'],['Dig list accuracy','+40%'],['Integrity reporting','automated']],demo:'#/lng/JT.trestle'},
 {id:'apc',tag:'APC',name:'APC & Yield Optimisation',short:'Model-predictive control on columns and compressors; energy and yield.',stages:['midstream','downstream'],
  match:/column|absorber|regenerator|fractionator|stripper|demethaniser|de-|reactor|heater|furnace|reboiler|compressor|exchanger|cold box|chiller|condenser/i,
  what:'Model-predictive controllers push columns, reactors and compressors to their constraints while an economic optimiser sets targets for yield and energy.',
  how:['Step tests and model identification','MPC on the DCS','Real-time optimiser for yield and energy','Twin shows constraint status per unit'],
  outcomes:[['Energy','-4%'],['Yield','+1.5%'],['Throughput','+2%']],demo:'#/refinery/CD.cdu'},
 {id:'emissions',tag:'Emissions',name:'Emissions & Flare Intelligence',short:'Methane, flaring and CO2 accounting from tags and vision.',stages:['upstream','midstream','downstream'],
  match:/flare|vent|stack|vru|vapour|tank|heater|furnace|boiler|generator|turbine/i,
  what:'Continuous emissions accounting from process tags, flare metering and camera analytics, with root-cause on every flaring event and audit-ready reporting.',
  how:['Flare and vent metering reconciled','Camera-based methane detection','Event root cause via the copilot','Regulatory reports generated monthly'],
  outcomes:[['Flaring','-25%'],['Reporting effort','-80%'],['Methane events found','3x']],demo:'#/production/FR.stack'},
 {id:'vision',tag:'Vision',name:'Vision Safety & Autonomous Inspection',short:'PPE, exclusion zones, drone and robot rounds, corrosion from imagery.',stages:['upstream','midstream','downstream'],
  match:/site|fence|pad|cellar|jetty|platform|tank|building|control|stair|rack/i,
  what:'Computer vision on fixed cameras, drones and ground robots: safety compliance in real time and inspection rounds that never miss a spot.',
  how:['Fixed-camera PPE and zone analytics','Drone and robot inspection routes','Corrosion and leak detection from imagery','Findings land on the twin'],
  outcomes:[['Round coverage','100%'],['Safety observations','+5x'],['Inspection cost','-30%']],demo:'#/lng/JT.platform'},
 {id:'sched',tag:'Scheduling',name:'LNG & Terminal Scheduling',short:'Berth, tank and train scheduling under constraints.',stages:['midstream'],
  match:/tank|jetty|arm|carrier|dolphin|train|loading|storage|bullet|sphere/i,
  what:'Optimisation of cargo, berth, tank inventory and train availability against contracts and weather, with demurrage exposure visible days ahead.',
  how:['Contract and shipping data integrated','Constraint-based schedule optimiser','Scenario what-ifs','Twin shows inventory and berth status'],
  outcomes:[['Demurrage','-20%'],['Tank utilisation','+6%'],['Schedule rework','-50%']],demo:'#/lng/SG.t1'},
 {id:'platform',tag:'Platform',name:'Data Platform & OT/IT Integration',short:'PI, historians, edge, MES/ERP connectors; the twin as the system of context.',stages:['upstream','midstream','downstream'],foundation:true,
  match:/./,
  what:'The foundation every solution runs on: historian and PI connectors, edge compute, an asset model that every tag, document and work order hangs off - which is what this twin is.',
  how:['PI / historian and SCADA connectors','Edge runtime for models','Asset model = the twin hierarchy','MES / ERP / CMMS integration'],
  outcomes:[['Weeks to first model','6'],['Tags onboarded','1,400+'],['Systems integrated','PI, CMMS, ERP']],demo:'#/chain'}
];
